import 'dart:async';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../models/app_user.dart';

class AuthService extends ChangeNotifier {
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  User? _currentUser;
  AppUser? _appUser;
  bool _isLoading = false;
  Timer? _heartbeatTimer;
  bool _isAppInForeground = true;

  User? get currentUser => _currentUser;
  AppUser? get appUser => _appUser;
  bool get isLoading => _isLoading;
  bool get isAuthenticated => _currentUser != null;
  
  bool get hasAutoGeneratedName {
    if (_appUser == null) return false;
    final name = _appUser!.displayName;
    return name.startsWith('User_') || name.startsWith('Agent ');
  }

  AuthService() {
    _auth.authStateChanges().listen(_onAuthStateChanged);
  }

  void setAppLifecycleState(bool isInForeground) {
    _isAppInForeground = isInForeground;
    
    if (isInForeground && _currentUser != null) {
      _startHeartbeat();
    } else {
      _stopHeartbeat();
      if (!isInForeground && _currentUser != null) {
        setOnlineStatus(false);
      }
    }
  }

  void _startHeartbeat() {
    _stopHeartbeat();
    _heartbeatTimer = Timer.periodic(const Duration(seconds: 45), (_) {
      if (_isAppInForeground && _currentUser != null) {
        setOnlineStatus(true);
      }
    });
    // Immediate update when starting
    setOnlineStatus(true);
  }

  void _stopHeartbeat() {
    _heartbeatTimer?.cancel();
    _heartbeatTimer = null;
  }

  Future<void> _onAuthStateChanged(User? user) async {
    _currentUser = user;
    if (user != null) {
      await _fetchOrCreateUserProfile(user);
      if (_isAppInForeground) {
        _startHeartbeat();
      }
    } else {
      _appUser = null;
      _stopHeartbeat();
    }
    notifyListeners();
  }

  Future<void> _fetchOrCreateUserProfile(User user) async {
    try {
      final docRef = _firestore.collection('users').doc(user.uid);
      final doc = await docRef.get();

      if (doc.exists && doc.data() != null) {
        try {
          _appUser = AppUser.fromMap(doc.data()!, user.uid);
        } catch (e) {
          // Handle malformed user data by creating a fresh profile
          debugPrint('[AuthService] Malformed user data, creating fresh profile: $e');
          await _createFreshUserProfile(user);
        }
      } else {
        await _createFreshUserProfile(user);
      }
    } catch (e) {
      debugPrint('[AuthService] Error fetching user profile: $e');
      // Create a local user profile even if Firestore fails
      final prefs = await SharedPreferences.getInstance();
      final savedName = prefs.getString('pg_display_name') ?? 'User_${user.uid.substring(0, 5)}';
      _appUser = AppUser(
        uid: user.uid,
        displayName: savedName,
        email: user.email,
        isOnline: true,
        lastSeen: DateTime.now(),
      );
    }
    notifyListeners();
  }

  Future<void> _createFreshUserProfile(User user) async {
    final prefs = await SharedPreferences.getInstance();
    final savedName = prefs.getString('pg_display_name') ?? 'User_${user.uid.substring(0, 5)}';
    _appUser = AppUser(
      uid: user.uid,
      displayName: savedName,
      email: user.email,
      isOnline: true,
      lastSeen: DateTime.now(),
    );
    
    try {
      final docRef = _firestore.collection('users').doc(user.uid);
      await docRef.set(_appUser!.toMap());
    } catch (e) {
      debugPrint('[AuthService] Error creating user profile in Firestore: $e');
      // Continue with local profile even if Firestore write fails
    }
  }

  Future<AppUser?> signInAnonymously({String? preferredName}) async {
    _isLoading = true;
    notifyListeners();
    try {
      final cred = await _auth.signInAnonymously();
      final user = cred.user;
      if (user != null) {
        final prefs = await SharedPreferences.getInstance();
        final name = preferredName ?? prefs.getString('pg_display_name') ?? 'User_${user.uid.substring(0, 5)}';
        if (preferredName != null) {
          await prefs.setString('pg_display_name', preferredName);
        }

        final docRef = _firestore.collection('users').doc(user.uid);
        _appUser = AppUser(
          uid: user.uid,
          displayName: name,
          isOnline: true,
          lastSeen: DateTime.now(),
        );
        
        try {
          await docRef.set(_appUser!.toMap(), SetOptions(merge: true));
        } catch (e) {
          debugPrint('[AuthService] Error writing user profile to Firestore: $e');
          // Continue with local profile even if Firestore write fails
        }
      }
      return _appUser;
    } catch (e) {
      debugPrint('[AuthService] Anonymous sign-in error: $e');
      rethrow;
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  Future<void> updateDisplayName(String newName) async {
    if (_currentUser == null) return;
    try {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString('pg_display_name', newName);

      _appUser = _appUser?.copyWith(displayName: newName);
      await _firestore.collection('users').doc(_currentUser!.uid).update({
        'displayName': newName,
        'lastSeen': FieldValue.serverTimestamp(),
      });
      notifyListeners();
    } catch (e) {
      debugPrint('[AuthService] Update name error: $e');
    }
  }

  Future<void> setOnlineStatus(bool isOnline) async {
    if (_currentUser == null) return;
    try {
      await _firestore.collection('users').doc(_currentUser!.uid).update({
        'isOnline': isOnline,
        'lastSeen': FieldValue.serverTimestamp(),
      });
    } catch (_) {}
  }

  Future<void> signOut() async {
    try {
      _stopHeartbeat();
      if (_currentUser != null) {
        await setOnlineStatus(false);
      }
      await _auth.signOut();
      _currentUser = null;
      _appUser = null;
      notifyListeners();
    } catch (e) {
      debugPrint('[AuthService] Sign out error: $e');
    }
  }
}
