import 'dart:io';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:provider/provider.dart';

import 'screens_new/app_navigation.dart';
import 'screens_new/call/name_selection_screen.dart';
import 'services/auth_service.dart';
import 'services/call_signaling_service.dart';
import 'services/in_app_calling_service.dart';
import 'services/phone_call_monitor.dart';
import 'state/session_controller.dart';
import 'theme/app_theme.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase (graceful if google-services.json is pending)
  try {
    await Firebase.initializeApp();
  } catch (e) {
    debugPrint('[PhaseGuard] Firebase initialization note: $e');
  }

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => SessionController()),
        ChangeNotifierProvider(create: (_) => AuthService()),
        ChangeNotifierProvider(create: (_) => CallSignalingService()),
        ChangeNotifierProvider(create: (_) => InAppCallingService()),
      ],
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'PhaseGuard',
      theme: PgTheme.data(),
      home: const MainScreen(),
      debugShowCheckedModeBanner: false,
    );
  }
}

class MainScreen extends StatefulWidget {
  const MainScreen({super.key});

  @override
  State<MainScreen> createState() => _MainScreenState();
}

class _MainScreenState extends State<MainScreen> with WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    WidgetsBinding.instance.addPostFrameCallback((_) => _bootstrapServices());
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    final auth = context.read<AuthService>();
    auth.setAppLifecycleState(false);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    final auth = context.read<AuthService>();
    final isInForeground = state == AppLifecycleState.resumed;
    auth.setAppLifecycleState(isInForeground);
  }

  Future<void> _bootstrapServices() async {
    final session = context.read<SessionController>();
    session.attachPhoneMonitor();

    // Anonymous authentication for in-app calling
    final auth = context.read<AuthService>();
    if (!auth.isAuthenticated) {
      try {
        await auth.signInAnonymously();
      } catch (e) {
        debugPrint('[PhaseGuard] Auth note: $e');
      }
    }

    if (!mounted) return;

    // Initialize Agora calling service in Testing Mode
    final calling = context.read<InAppCallingService>();
    try {
      await calling.initialize();
    } catch (e) {
      debugPrint('[PhaseGuard] Agora init note: $e');
    }

    if (Platform.isAndroid) {
      await Permission.phone.request();
      await Permission.notification.request();
      await Permission.microphone.request();
    }

    try {
      await PhoneCallMonitor.start();
    } catch (_) {}
  }

  @override
  Widget build(BuildContext context) {
    final auth = context.watch<AuthService>();
    
    // Show name selection screen if user has auto-generated name
    if (auth.isAuthenticated && auth.hasAutoGeneratedName) {
      return const NameSelectionScreen();
    }
    
    return const AppNavigation();
  }
}