import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../services/auth_service.dart';
import '../../theme/tokens.dart';
import '../../widgets/app_background.dart';

class NameSelectionScreen extends StatefulWidget {
  const NameSelectionScreen({super.key});

  @override
  State<NameSelectionScreen> createState() => _NameSelectionScreenState();
}

class _NameSelectionScreenState extends State<NameSelectionScreen> {
  final TextEditingController _nameController = TextEditingController();
  bool _isLoading = false;
  String? _errorMessage;

  @override
  void dispose() {
    _nameController.dispose();
    super.dispose();
  }

  Future<void> _saveName() async {
    final name = _nameController.text.trim();
    if (name.isEmpty) {
      setState(() => _errorMessage = 'Please enter your name');
      return;
    }

    if (name.length < 2) {
      setState(() => _errorMessage = 'Name must be at least 2 characters');
      return;
    }

    setState(() {
      _isLoading = true;
      _errorMessage = null;
    });

    try {
      final auth = context.read<AuthService>();
      await auth.updateDisplayName(name);

      if (mounted) {
        // If opened from hub "Change name", pop back.
        // If shown as first-run root screen, main.dart rebuilds automatically
        // once hasAutoGeneratedName becomes false — no pop needed.
        if (Navigator.of(context).canPop()) {
          Navigator.of(context).pop();
        }
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _isLoading = false;
          _errorMessage = 'Failed to save name: ${e.toString()}';
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.transparent,
      body: AppBackground(
        child: SafeArea(
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: PgSpace.lg, vertical: PgSpace.xl),
            child: Column(
              children: [
                const SizedBox(height: 20),
                // Header
                const Text(
                  'Choose Your Name',
                  style: TextStyle(
                    fontSize: 28,
                    fontWeight: FontWeight.bold,
                    color: PgColors.textPrimary,
                  ),
                ),
                
                const Spacer(),
                
                // Icon
                Container(
                  width: 100,
                  height: 100,
                  decoration: BoxDecoration(
                    shape: BoxShape.circle,
                    gradient: LinearGradient(
                      colors: [
                        PgColors.accent.withValues(alpha: 0.3),
                        PgColors.accent.withValues(alpha: 0.1),
                      ],
                      begin: Alignment.topLeft,
                      end: Alignment.bottomRight,
                    ),
                    border: Border.all(color: PgColors.accent, width: 2),
                  ),
                  child: const Icon(
                    Icons.person,
                    size: 50,
                    color: PgColors.accent,
                  ),
                ),
                
                const SizedBox(height: 32),
                
                // Description
                const Text(
                  'How should other users see you?',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.w600,
                    color: PgColors.textPrimary,
                  ),
                  textAlign: TextAlign.center,
                ),
                
                const SizedBox(height: 8),
                
                Text(
                  'This name will be shown to other users when you make protected calls.',
                  style: TextStyle(
                    fontSize: 14,
                    color: PgColors.textSecondary.withValues(alpha: 0.9),
                  ),
                  textAlign: TextAlign.center,
                ),
                
                const SizedBox(height: 32),
                
                // Name input
                TextField(
                  controller: _nameController,
                  decoration: InputDecoration(
                    hintText: 'Enter your name',
                    filled: true,
                    fillColor: PgColors.bgSecondary.withValues(alpha: 0.5),
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(PgRadii.card),
                      borderSide: BorderSide(color: PgColors.border),
                    ),
                    enabledBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(PgRadii.card),
                      borderSide: BorderSide(color: PgColors.border),
                    ),
                    focusedBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(PgRadii.card),
                      borderSide: BorderSide(color: PgColors.accent, width: 2),
                    ),
                    errorText: _errorMessage,
                  ),
                  style: const TextStyle(color: PgColors.textPrimary),
                  textCapitalization: TextCapitalization.words,
                  maxLength: 30,
                  autofocus: true,
                ),
                
                const SizedBox(height: 24),
                
                // Save button
                SizedBox(
                  width: double.infinity,
                  height: 50,
                  child: ElevatedButton(
                    onPressed: _isLoading ? null : _saveName,
                    style: ElevatedButton.styleFrom(
                      backgroundColor: PgColors.accent,
                      foregroundColor: PgColors.bgPrimary,
                      disabledBackgroundColor: PgColors.textMuted,
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(PgRadii.card),
                      ),
                    ),
                    child: _isLoading
                        ? const SizedBox(
                            height: 20,
                            width: 20,
                            child: CircularProgressIndicator(
                              strokeWidth: 2,
                              valueColor: AlwaysStoppedAnimation<Color>(PgColors.bgPrimary),
                            ),
                          )
                        : const Text(
                            'Save Name',
                            style: TextStyle(
                              fontSize: 16,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                  ),
                ),
              
              const Spacer(),
            ],
          ),
        ),
      ),
    ),
  );
  }
}
